[package]
name = "dantalian"
version = "0.3.0"
authors = ["Nanozuki Crows <nanozuki.crows@gmail.com>"]
edition = "2018"
description = "A nfo file generator for your anime. Source from https://bangumi.tv/."
license = "GPL-3.0-or-later"
repository = "https://github.com/nanozuki/dantalian/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = "1.0.61"
serde_repr = "0.1.6"
hyper = { version = "0.14.2", features = ["http1", "http2", "client", "runtime"] }
tokio = { version = "1.0.1", features = ["full"] }
anyhow = "1.0.37"
futures = "0.3.9"
percent-encoding = "2.1.0"
hyper-tls = "0.5.0"
tinytemplate = "1.2.0"
walkdir = "2.3.1"
regex = "1.4.3"
toml = "0.5"
log = "0.4"
once_cell = "1.7"
colored = "2.0.0"
regex-gather = { git = "https://github.com/laxect/regex-gather.git" }

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
